Prenda.create! tipo: "Remera manga corta", categoria: :Torso, tela: "algodon", color_p: "verde", color_s: "azul"
Prenda.create! tipo: "Remera manga larga", categoria: :Torso, tela: "mohair", color_p: "azul"
Prenda.create! tipo: "Botas militares", categoria: :Pies, tela: "lino", color_p: "gris", color_s: "negro"
Prenda.create! tipo: "Pantalon de Jean", categoria: :Piernas, tela: "lana", color_p: "amarillo"
Prenda.create! tipo: "Camisa negra", categoria: :Torso, tela: "piel", color_p: "fucsia", color_s: "amarillo"
Prenda.create! tipo: "Bandana Azul", categoria: :Accesorio, tela: "seda", color_p: "blanco", color_s: "negro"
Prenda.create! tipo: "Pollera amarilla", categoria: :Piernas, tela: "mohair", color_p: "violeta", color_s: "rojo"
Prenda.create! tipo: "Remera manga corta", categoria: :Torso, tela: "lana", color_p: "verde"
Prenda.create! tipo: "Remera manga larga", categoria: :Torso, tela: "lino", color_p: "rojo", color_s: "amarillo"
Prenda.create! tipo: "Botas militares", categoria: :Pies, tela: "algodon", color_p: "naranja"